stages:
 - build
 - deploy

pull_git:
 stage: build
 script:
  - sudo npm install create-react-app -g
  - cd client
  - rm -rf node_modules
  - docker run build -t snack-order-client .
  - CI=false npm run build

deploy_production:
 stage: deploy
 script:
  - pwd
  - ls