stages:
 - build
 - deploy

pull_git:
 stage: build
 script:
  # - sudo npm install create-react-app -g
  - docker login -u kieutridang -p Tridang93
  - docker build -t snack-order-client ./client

deploy_production:
 stage: deploy
 script:
  - pwd
  - ls