stages:
 - build
 - deploy

pull_git:
 stage: build
 script:
  - git checkout dev
  - git stash
  - git pull https://kieutridang:Ktd93Nth91@github.com/SmithWinter/Snack-Order.git dev

deploy_production:
 stage: deploy
 script:
  - cd client
  - source ~/.profile
  - npm install
  - npm run build
  - cd ../server
