stages:
 - build
 - deploy

pull_git:
 stage: build
 script:
  - git checkout dev
  - git stash
  - git pull https://kieutridang:Ktd93Nth91@github.com/SmithWinter/Snack-Order.git dev
  - cd client
  - docker run build -t snack-order-client

deploy_production:
 stage: deploy
 script:
  - cd ../server
  - npm start
