stages:
 - build
 - deploy

pull_git:
 stage: build
 script:
  - npm install create-react-app -g
  - git checkout dev
  - git stash
  - git pull https://kieutridang:Ktd93Nth91@github.com/SmithWinter/Snack-Order.git dev
  - cd client
  - npm install
  - npm run build

deploy_production:
 stage: deploy
 script:
  - cd ../server
  - npm install
  - npm start
