stages:
 - build
 - deploy

pull_git:
 stage: build
 script:
  - sudo npm install create-react-app -g
  - git checkout dev
  - git stash
  - git pull https://kieutridang:Ktd93Nth91@github.com/SmithWinter/Snack-Order.git dev
  - cd client
  - rm -rf node_modules
  - npm install
  - CI=false npm run build

deploy_production:
 stage: deploy
 script:
  - pwd
  - cd server
  - npm install
  - npm start